import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { parse } from "../src/yaml.js";

// We exercise the compiled dist/cli.js to match how users invoke it.
// The `build` lifecycle runs before the test in CI (npm run build && npm test).
// Locally, the file is generated by `npm run build`; the test skips when absent.

const CLI = resolve(__dirname, "..", "dist", "cli.js");
const FIXTURE = resolve(__dirname, "..", "testdata", "example-scenario.ts");

const runCLI = (args: string[]): string =>
  execFileSync("node", [CLI, ...args], { encoding: "utf8" });

describe("edt-ts CLI", () => {
  if (!existsSync(CLI)) {
    it.skip("dist/cli.js not built — run `npm run build` first", () => {});
    return;
  }

  it("prints usage on --help", () => {
    const out = runCLI(["--help"]);
    expect(out).toContain("edt-ts <command>");
    expect(out).toContain("compile");
  });

  it("compile writes canonical YAML to stdout", () => {
    const out = runCLI(["compile", FIXTURE]);
    const parsed = parse(out);
    expect(parsed.metadata.name).toBe("example-from-ts");
    expect(parsed.spec.steps).toHaveLength(1);
  });

  it("compile -o writes to file", () => {
    const dir = mkdtempSync(join(tmpdir(), "edt-ts-"));
    try {
      const out = join(dir, "out.yaml");
      runCLI(["compile", FIXTURE, "-o", out]);
      const parsed = parse(readFileSync(out, "utf8"));
      expect(parsed.metadata.name).toBe("example-from-ts");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("exits non-zero for an unknown export shape", () => {
    const dir = mkdtempSync(join(tmpdir(), "edt-ts-bad-"));
    try {
      mkdirSync(dir, { recursive: true });
      const bad = join(dir, "bad.ts");
      // Write a TS file whose default export is not a Scenario.
      writeFileSync(bad, "export default { not: 'a scenario' };\n");
      expect(() => runCLI(["compile", bad])).toThrow();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
