{{- if and .Values.controlPlane.enabled .Values.controlPlane.adminToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edt.adminSecretName" . }}
  labels:
    {{- include "edt.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.controlPlane.adminToken | quote }}
{{- end -}}
