{{- if and .Values.controlPlane.enabled .Values.controlPlane.workerToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edt.workerSecretName" . }}
  labels:
    {{- include "edt.labels" . | nindent 4 }}
type: Opaque
stringData:
  worker-token: {{ .Values.controlPlane.workerToken | quote }}
{{- end -}}
